import { Injectable, Inject, Logger } from '@nestjs/common';
import { randomUUID } from 'crypto';
import type { Job } from 'pg-boss';
import { CertificateService } from '../../certificates/certificate.service';
import { CertificatePdfService } from '../../certificates/certificate-pdf.service';
import { STORAGE_PORT, type StoragePort } from '../../../common/storage/storage.port';
import type { GenerateCertificatePdfPayload } from '../job.types';

// ─── GenerateCertificatePdfHandler ───────────────────────────────────────────
// Generates and stores a PDF version of an AcceptanceCertificate.
//
// Triggered by:
//   IssueCertificateHandler enqueues this job immediately after the certificate
//   row is persisted, using singletonKey = "generate-certificate-pdf:{certId}".
//
// Idempotency:
//   If pdfStorageKey is already set on the certificate, the handler exits
//   immediately — a previous run already completed successfully.
//   Re-running the handler with the same certificateId is always safe.
//
// Storage key format:
//   certificates/{certificateId}.pdf
//
// Retry policy (set on queue): 3 attempts with exponential backoff.
//   PDF generation reads immutable tables; S3 writes are idempotent.
//
// Observability events (all structured JSON):
//   pdf_job_started         — logged at the start of every attempt
//   pdf_already_generated   — logged when pdfStorageKey is already set (idempotent skip)
//   pdf_generation_complete — logged on success (includes storageKey)
//   pdf_generation_failed   — logged on failure (before rethrow)

@Injectable()
export class GenerateCertificatePdfHandler {
  private readonly logger = new Logger(GenerateCertificatePdfHandler.name);

  constructor(
    private readonly certificateService: CertificateService,
    private readonly pdfService: CertificatePdfService,
    @Inject(STORAGE_PORT) private readonly storage: StoragePort,
  ) {}

  async handle(jobs: Job<GenerateCertificatePdfPayload>[]): Promise<void> {
    for (const job of jobs) {
      const { certificateId } = job.data;
      const traceId = randomUUID();

      this.logger.log(JSON.stringify({
        event: 'pdf_job_started',
        traceId,
        jobId: job.id,
        certificateId,
      }));

      try {
        // Idempotency: skip if PDF was already generated by a previous attempt.
        const cert = await this.certificateService.getExportForJob(certificateId);
        if (cert.pdfStorageKey) {
          this.logger.log(JSON.stringify({
            event: 'pdf_already_generated',
            traceId,
            jobId: job.id,
            certificateId,
            storageKey: cert.pdfStorageKey,
          }));
          continue;
        }

        // Generate PDF bytes from the certificate payload.
        const pdfBytes = await this.pdfService.generate({
          certificateId: cert.certificateId,
          certificateHash: cert.certificateHash,
          issuedAt: cert.issuedAt,
          payload: cert.payload,
        });

        // Upload to storage.
        const storageKey = `certificates/${certificateId}.pdf`;
        await this.storage.putBuffer(storageKey, 'application/pdf', Buffer.from(pdfBytes));

        // Record the key on the certificate row.
        await this.certificateService.setPdfStorageKey(certificateId, storageKey);

        this.logger.log(JSON.stringify({
          event: 'pdf_generation_complete',
          traceId,
          jobId: job.id,
          certificateId,
          storageKey,
          sizeBytes: pdfBytes.byteLength,
        }));
      } catch (err) {
        this.logger.error(
          JSON.stringify({
            event: 'pdf_generation_failed',
            traceId,
            jobId: job.id,
            certificateId,
          }),
          err instanceof Error ? err.stack : String(err),
        );
        throw err;
      }
    }
  }
}
